# Generated by Django 4.2.7 on 2023-11-10 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmates', '0003_alter_classmate_address_alter_classmate_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmate',
            name='address',
            field=models.CharField(default='No Address Provided', max_length=200),
        ),
        migrations.AlterField(
            model_name='classmate',
            name='gender',
            field=models.CharField(default='No Address Provided', max_length=200),
        ),
    ]
